config/routes.rb
Rails.application.routes.draw do

root to: 'homes#top'
get 'home/top' => 'homes#top'

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
}
  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  scope module: :public do
    resources :main_contents, only: [:index, :show] do
     resource :likes, only: [:create, :destroy]

     resources :main_comments, only: [:create, :destroy]
    end
    resources :events, only: [:index]
    resources :boards do
    resources :board_comments, only: [:create, :destroy]
  end
    resources :inquiries, only: [:index, :new, :create,]
    get 'inquiries/complete'
  end

  namespace :admin do
   resources :main_contents
   resources :events
   resources :boards, only: [:index, :show, :destroy]
   resources :inquiries, only: [:index, :show]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :main_contents, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
   belongs_to :customer
   has_many :post_comments, dependent: :destroy
   has_many :board_comments, dependent: :destroy
end

app/models/board_comment.rb
class BoardComment < ApplicationRecord
  belongs_to :customer
  belongs_to :board
end

app/models/comment_main.rb
class CommentMain < ApplicationRecord
  belongs_to :customer
  belongs_to :main_content
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :board_comments, dependent: :destroy
  has_many :main_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :customer
  belongs_to :main_content
  
end

app/models/main_comment.rb
class MainComment < ApplicationRecord
  belongs_to :customer
  belongs_to :main_content

end

app/models/main_content.rb
class MainContent < ApplicationRecord

  # belongs_to :customer
  has_many :main_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked_by?(customer)
     likes.where(customer_id: customer.id).exists?
  end

  belongs_to :admins, optional: true
  attachment :image
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    @boards = Board.all
    @board = Board.find(params[:id])
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to admin_boards_path
  end

  private
  def board_params
    params.require(:board).permit(:title, :sentence, :name, :board_id, :created_at, :board_id)
  end

end

app/controllers/admin/main_contents_controller.rb
class Admin::MainContentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @main_contents = MainContent.all
  end

  def show
    @main_content = MainContent.find(params[:id])
    @main_comment = MainComment.new
  end

  def new
    @main_content = MainContent.new
  end

  def create
    @main_content = MainContent.new(main_content_params)
    @main_content.score = Language.get_data(main_content_params[:appeal])  #API
    if @main_content.save
    redirect_to admin_main_contents_path
    else
      render :new
    end
  end

  def edit
    @main_content = MainContent.find(params[:id])
  end

  def update
    @main_content = MainContent.find(params[:id])
    @main_content.update(main_content_params)
    redirect_to admin_main_content_path(@main_content.id)
  end

  def destroy
    @main_content = MainContent.find(params[:id])
    @main_content.destroy
    redirect_to admin_main_contents_path
  end


  private
  def main_content_params
    params.require(:main_content).permit(:facility, :time, :appeal, :fee, :address, :access, :admin_id,:image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_up_path_for(resource)
    main_contents_path
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_main_contents_path          #pathは設定したい遷移先へのpathを指定してください
    when Customer
      main_contents_path              #ここもpathはご自由に変更してください
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/boards_helper.rb
module Admin::BoardsHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/helpers/admin/main_contents_helper.rb
module Admin::MainContentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_comments_helper.rb
module BoardCommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/main_comments_helper.rb
module MainCommentsHelper
end

app/views/admin/main_contents/_form.html.erb
  <h4>施設名</h4>
  <%= f.text_field :facility %>

  <h4>営業時間</h4>
  <%= f.text_field :time %>

  <h4>説明文</h4>
  <%= f.text_area :appeal %>

  <h4>料金</h4>
  <%= f.text_field :fee %>

  <h4>住所</h4>
  <%= f.text_field :address %>

  <h4>アクセス</h4>
  <%= f.text_field :access %>

<h4>画像</h4>
<%= f.attachment_field :image %>

app/views/admin/main_contents/edit.html.erb
<h4>投稿編集</h4>

<%= form_with model: [:admin, @main_content], local:true do |f| %>

<%= render "form", f: f %>

<%= f.submit '更新' %>

<% end %>

app/views/admin/main_contents/index.html.erb
<h4>投稿一覧</h4>
 <%= link_to "新規投稿", new_admin_main_content_path, class: "btn btn-success" %>

  <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>投稿ID</th>
          <th>施設名</th>
          <th>住所</th>
        </tr>
      </thead>
     <tbody>
　　　<% @main_contents.each do |main_content| %>
　　　　 <tr>
　　　　　<td><%= main_content.id %></td>
　　　　　<td><%= link_to main_content.facility,admin_main_content_path(main_content.id) %></td>
　　　　　<td><%= main_content.address %></td>
　　　　 </tr>
      <% end %>
     </tbody>
  </table>

app/views/admin/main_contents/new.html.erb
<h2>新規投稿</h2>
<!-- form_with部分 -->
<%= form_with model: [:admin, @main_content], local:true do |f| %>

<%= render "form", f: f %>

<%= f.submit '投稿' %>

<% end %>

app/views/admin/main_contents/show.html.erb
<body>

<h4>投稿詳細</h4>

<table class="table table-hover table-inverse">
      <tr>
       <td>施設名</td>
         <td>
          <%= @main_content.facility %>
         </td>
      </tr>
      <tr>
       <td>営業時間</td>
         <td>
          <%= @main_content.time %>
         </td>
      </tr>
      <tr>
       <td>説明文</td>
        <td>
          <%= @main_content.appeal %>
          <p class="sentiment-score">本文の感情分析スコア[<%= @main_content.score %>]</p>
        </td>
      </tr>
      <tr>
       <td>料金</td>
        <td>
          <%= @main_content.fee %>
        </td>
      </tr>
      <tr>
       <td>住所</td>
        <td>
          <%= @main_content.address %>
        </td>
      </tr>
      <tr>
       <td>アクセス</td>
        <td>
          <%= @main_content.access %>
        </td>
      </tr>
      <tr>
       <td>コメント一覧</td>
        <td>
         <% @main_content.main_comments.each do |main_comment| %>
          <div><%= main_comment.comment_content %></div>
          <% end %>
        </td>
      </tr>
      <%= @main_content.likes.count %> いいね
      <%if @main_content.image_id.nil? %>
      画像なし
      <%else%>
      <%= image_tag attachment_url(@main_content, :image, :fill, 300, 300, format: "jpg") %>
      <%end %>
      <%= link_to "編集", edit_admin_main_content_path(@main_content.id), class: "btn btn-success" %>
      <%= link_to "削除", admin_main_content_path(@main_content.id), method: :delete, class: "btn btn-danger" %>
      <%= link_to "一覧", admin_main_contents_path(@main_content.id), class: "btn btn-primary" %>
</table>
</body>