config/routes.rb
Rails.application.routes.draw do

root to: 'homes#top'
get 'home/top' => 'homes#top'

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
}
  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  scope module: :public do
    resources :main_contents, only: [:index, :show] do
     resource :likes, only: [:create, :destroy]

     resources :main_comments, only: [:create, :destroy]
    end
    resources :events, only: [:index]
    resources :boards do
    resources :board_comments, only: [:create, :destroy]
  end
    resources :inquiries, only: [:index, :new, :create,]
    get 'inquiries/complete'
  end

  namespace :admin do
   resources :main_contents
   resources :events
   resources :boards, only: [:index, :show, :destroy]
   resources :inquiries, only: [:index, :show]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :main_contents, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
   belongs_to :customer
   has_many :post_comments, dependent: :destroy
   has_many :board_comments, dependent: :destroy
end

app/models/board_comment.rb
class BoardComment < ApplicationRecord
  belongs_to :customer
  belongs_to :board
end

app/models/comment_main.rb
class CommentMain < ApplicationRecord
  belongs_to :customer
  belongs_to :main_content
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :board_comments, dependent: :destroy
  has_many :main_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :customer
  belongs_to :main_content
  
end

app/models/main_comment.rb
class MainComment < ApplicationRecord
  belongs_to :customer
  belongs_to :main_content

end

app/models/main_content.rb
class MainContent < ApplicationRecord

  # belongs_to :customer
  has_many :main_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked_by?(customer)
     likes.where(customer_id: customer.id).exists?
  end

  belongs_to :admins, optional: true
  attachment :image
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    @boards = Board.all
    @board = Board.find(params[:id])
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to admin_boards_path
  end

  private
  def board_params
    params.require(:board).permit(:title, :sentence, :name, :board_id, :created_at, :board_id)
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
    redirect_to admin_events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to admin_event_path(@event.id)

  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to admin_events_path
  end


  private
  def event_params
    params.require(:event).permit(:festival, :place, :period)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_up_path_for(resource)
    main_contents_path
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_main_contents_path          #pathは設定したい遷移先へのpathを指定してください
    when Customer
      main_contents_path              #ここもpathはご自由に変更してください
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/boards_helper.rb
module Admin::BoardsHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/helpers/admin/main_contents_helper.rb
module Admin::MainContentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_comments_helper.rb
module BoardCommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/main_comments_helper.rb
module MainCommentsHelper
end

app/views/admin/boards/index.html.erb
<h4>掲示板一覧</h4>
 <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>投稿ID</th>
          <th>投稿時間</th>
          <th>タイトル</th>
          <th>投稿者</th>
        </tr>
      </thead>
     <tbody>
       <% @boards.each do |board| %>
         <tr>
　　　　　<td><%= board.id %></td>
　　　　　<td><%= board.created_at %></td>
　　　　　<td><%= link_to board.title,admin_board_path(board.id) %></td>
　　　　　<td><%= board.name %></td>
　　　　 </tr>
       <% end %>
     </tbody>
  </table>

app/views/admin/boards/show.html.erb
<h4>掲示板詳細</h4>

<table class="table table-hover table-inverse">
      <tr>
       <td>投稿ID</td>
         <td>
          <%= @board.id %>
         </td>
      </tr>
      <tr>
       <td>投稿日時</td>
         <td>
          <%= @board.created_at %>
         </td>
      </tr>
      <tr>
       <td>投稿者</td>
        <td>
          <%= @board.name %>
        </td>
      </tr>
      <tr>
       <td>タイトル</td>
        <td>
          <%= @board.title %>
        </td>
      </tr>
      <tr>
       <td>本文</td>
        <td>
          <%= @board.sentence %>
        </td>
      </tr>
      <%= link_to "削除", admin_board_path(@board.id), method: :delete, class: "btn btn-danger" %>
      <%= link_to "一覧", admin_boards_path(@board.id), class: "btn btn-primary" %>
  </table>

app/views/admin/events/_form.html.erb
  <h4>日時</h4>
  <%= f.text_field :period %>

  <h4>開催場所</h4>
  <%= f.text_field :place %>

  <h4>イベント名</h4>
  <%= f.text_area :festival %>

app/views/admin/events/edit.html.erb
<h4>投稿編集</h4>

<%= form_with model: [:admin, @event], local:true do |f| %>

<%= render "form", f: f %>

<%= f.submit '更新' %>

<% end %>

app/views/admin/events/index.html.erb
<h4>イベント一覧</h4>
<%= link_to "新規投稿", new_admin_event_path, class: "btn btn-success" %>

 <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>投稿ID</th>
          <th>日付</th></th>
          <th>開催場所</th>
          <th>イベント名</th>
        </tr>
      </thead>
     <tbody>
       <% @events.each do |event| %>
          <tr>
　　　　　<td><%= event.id %></td>
　　　　　<td><%= event.period %></td>
　　　　　<td><%= event.place %></td>
　　　　　<td><%= link_to event.festival,admin_event_path(event.id) %></td>
　　　　 </tr>
      <% end %>
     </tbody>
  </table>

app/views/admin/events/new.html.erb
<h2>新規投稿</h2>
<!-- form_with部分 -->
<%= form_with model: [:admin, @event], local:true do |f| %>

<%= render "form", f: f %>

<%= f.submit '投稿' %>

<% end %>

app/views/admin/events/show.html.erb
<h4>投稿詳細</h4>

<table class="table table-hover table-inverse">
      <tr>
       <td>日時</td>
         <td>
          <%= @event.period %>
         </td>
      </tr>
      <tr>
       <td>開催場所</td>
         <td>
          <%= @event.place %>
         </td>
      </tr>
      <tr>
       <td>イベント名</td>
        <td>
          <%= @event.festival %>
        </td>
      </tr>
      <%= link_to "編集", edit_admin_event_path(@event.id), class: "btn btn-success" %>
      <%= link_to "削除", admin_event_path(@event.id), method: :delete, class: "btn btn-danger" %>
      <%= link_to "一覧", admin_events_path(@event.id), class: "btn btn-primary" %>
</table>