config/routes.rb
Rails.application.routes.draw do

root to: 'homes#top'
get 'home/top' => 'homes#top'

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
}
  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  scope module: :public do
    resources :main_contents, only: [:index, :show] do
     resource :likes, only: [:create, :destroy]

     resources :main_comments, only: [:create, :destroy]
    end
    resources :events, only: [:index]
    resources :boards do
    resources :board_comments, only: [:create, :destroy]
  end
    resources :inquiries, only: [:index, :new, :create,]
    get 'inquiries/complete'
  end

  namespace :admin do
   resources :main_contents
   resources :events
   resources :boards, only: [:index, :show, :destroy]
   resources :inquiries, only: [:index, :show]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :main_contents, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
   belongs_to :customer
   has_many :post_comments, dependent: :destroy
   has_many :board_comments, dependent: :destroy
end

app/models/board_comment.rb
class BoardComment < ApplicationRecord
  belongs_to :customer
  belongs_to :board
end

app/models/comment_main.rb
class CommentMain < ApplicationRecord
  belongs_to :customer
  belongs_to :main_content
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :board_comments, dependent: :destroy
  has_many :main_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :customer
  belongs_to :main_content
  
end

app/models/main_comment.rb
class MainComment < ApplicationRecord
  belongs_to :customer
  belongs_to :main_content

end

app/models/main_content.rb
class MainContent < ApplicationRecord

  # belongs_to :customer
  has_many :main_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked_by?(customer)
     likes.where(customer_id: customer.id).exists?
  end

  belongs_to :admins, optional: true
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_up_path_for(resource)
    main_contents_path
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_main_contents_path          #pathは設定したい遷移先へのpathを指定してください
    when Customer
      main_contents_path              #ここもpathはご自由に変更してください
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/boards_helper.rb
module Admin::BoardsHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_comments_helper.rb
module BoardCommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/main_comments_helper.rb
module MainCommentsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_adminheader.html.erb
<header>
<nav class="navbar navbar-expand-md  navbar-dark" style="background-color:#0E4D52;">

  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#bs-navi" aria-controls="bs-navi" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="bs-navi">
    <font color="white"><h3>Planet Watcher</h3></font>

    <ul class="navbar-nav ml-auto">
      <%= link_to admin_main_contents_path do %>
       <font color="white"><ruby><h2>MAIN.</h2><rt>プラネタリウム紹介</rt></ruby></font>
      <% end %>
      <%= link_to admin_events_path do %>
       <font color="white"><ruby><h2>EVENT.</h2><rt>イベント予定</rt></ruby></font>
      <% end %>
      <%= link_to admin_boards_path do %>
       <font color="white"><ruby><h2>BBS.</h2><rt>掲示板</rt></ruby></font>
      <% end %>
      <%= link_to admin_inquiries_path do %>
       <font color="white"><ruby><h2>INFO.</h2><rt>問い合わせ</rt></ruby></font>
      <% end %>
    </ul>

  <%= link_to destroy_admin_session_path, method: :delete do %>
      <button type="button" class="btn btn-outline-info btn-sm">ログアウト</button>
      <% end %>
  </div>
</nav>
</header>

app/views/layouts/_customerheader.html.erb
<header>
<nav class="navbar navbar-expand-md  navbar-dark" style="background-color:#0E4D52;">

  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#bs-navi" aria-controls="bs-navi" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="bs-navi">
    <font color="white"><h3>Planet Watcher</h3></font>

    <ul class="navbar-nav ml-auto">
      <%= link_to main_contents_path do %>
       <font color="white"><ruby><h2>MAIN.</h2><rt>プラネタリウム紹介</rt></ruby></font>
      <% end %>
      <%= link_to events_path do %>
       <font color="white"><ruby><h2>EVENT.</h2><rt>イベント予定</rt></ruby></font>
      <% end %>
      <%= link_to boards_path do %>
       <font color="white"><ruby><h2>BBS.</h2><rt>掲示板</rt></ruby></font>
      <% end %>
      <%= link_to new_inquiry_path do %>
       <font color="white"><ruby><h2>INFO.</h2><rt>問い合わせ</rt></ruby></font>
      <% end %>
    </ul>
    <%= link_to destroy_customer_session_path, method: :delete do %>
      <button type="button" class="btn btn-outline-info btn-sm">ログアウト</button>
    <% end %>
  </div>
</nav>
</header>

app/views/layouts/_footer.html.erb
<div class="wrapper">
    <div class="container">
    </div>
　　<footer>
  　　<p>2021-2022 PLANET WATCHER. ALL Rights Reserved.</p>
　　</footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanetWatcher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if admin_signed_in? %>
     <%= render "layouts/adminheader" %>
    <% elsif customer_signed_in? %>
     <%= render "layouts/customerheader" %>
    <% else %>
     <%= render "layouts/header" %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>